# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 13:21
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('aklub', '0002_auto_20171109_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=30, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=100, verbose_name='Telephone'),
        ),
    ]
